name:                'y'
version:             0.1.0.0
github:              "github.com/gabriel128/y"
license:             BSD3
author:              "Gabriel Torello"
copyright:           "2022 Gabriel Torello"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/y#readme>

dependencies:
- base >=4.9 && <4.20
- mtl
- text
- containers
- either
- random
- megaparsec
- neat-interpolation
- fused-effects >= 1.1.2.2
- parser-combinators
- process
- cmdargs

library:
  source-dirs:
    - src

executables:
  yc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Werror
    - -Wall
    - -Wincomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 'y'
    when:
    - condition: false
      other-modules: Paths_y

tests:
  y-test:
    main:                TestLoader.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 'y'
    - tasty
    - doctest-parallel
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-classes

default-extensions:
  - MultiWayIf
  - TupleSections
  - NumericUnderscores
  - NamedFieldPuns
  - RecordWildCards
  - InstanceSigs
  - ConstrainedClassMethods
  - DisambiguateRecordFields
  - OverloadedStrings
  - Strict
  - StrictData
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - TypeApplications
  - TypeOperators
  - UndecidableInstances
  - RankNTypes
