name:                yacll
version:             0.1.0.0
github:              "githubuser/yacll"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/yacll#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- containers
- either
- random
- megaparsec
- neat-interpolation
- fused-effects >= 1.1.2.0

library:
  source-dirs:
    - src

executables:
  yacll-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Werror
    - -Wall
    - -Wincomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yacll
    when:
    - condition: false
      other-modules: Paths_yacll

tests:
  yacll-test:
    main:                TestLoader.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yacll
    - tasty
    - doctest-parallel
    - tasty-hunit
    - tasty-smallcheck

default-extensions:
  - MultiWayIf
  - TupleSections
  - NumericUnderscores
  - NamedFieldPuns
  - RecordWildCards
  - InstanceSigs
  - ConstrainedClassMethods
  - DisambiguateRecordFields
  - OverloadedStrings
  - Strict
  - StrictData
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - TypeApplications
  - TypeOperators
  - UndecidableInstances
  - RankNTypes
