ghc-options:
  yacll: -Wall
packages:
- .
resolver:  lts-21.21
  # compiler: ghc-8.10.7

extra-deps:
  - doctest-parallel-0.2.4
  - fused-effects-1.1.2.2
  - Cabal-3.6.3.0
#   - either-5.0.2
#   - string-random-0.1.4.2

# allow-newer: true
