ghc-options:
  yacll: -Wall
packages:
- .
resolver:  lts-18.28
  # compiler: ghc-8.10.7

extra-deps:
  - doctest-parallel-0.2.4
  - fused-effects-1.1.2.0
  - Cabal-3.6.3.0
#   - either-5.0.2
#   - string-random-0.1.4.2

# allow-newer: true
# docker:
#   enable: true
#   repo: "fpco/stack-build:lts-18.28"
#   mount-mode: delegated
  # persist: true
  # network: host
  # run-args: ["--net=bridge"]
  # stack-exe: download
